import type { DashboardNavItem } from "@/lib/dashboard/navigation";
import type { SiteSettings } from "@/lib/cms/types";

export const homeThemeKeys = [
  "default",
  "modern-marketplace",
  "luxury-commerce",
  "minimal-storefront",
  "bold-catalog",
] as const;

export const defaultSiteSettings: SiteSettings = {
  siteName: "Alışveriş",
  shortName: "Alışveriş",
  logoUrl: "",
  darkLogoUrl: "",
  faviconUrl: "",
  defaultSeoTitle: "Alışveriş - Marketplace, mağaza və elan platforması",
  defaultMetaDescription:
    "Azərbaycanda məhsul satışı, mağaza idarəetməsi, elan yerləşdirmə və sifarişlər üçün marketplace platforması.",
  defaultSeoKeywords:
    "alışveriş, marketplace, məhsul satışı, elan, mağaza",
  contactEmail: "",
  phone: "",
  whatsapp: "",
  address: "",
  socialLinks: {},
  copyrightText: "© Alışveriş",
  maintenanceMode: false,
  userRegistrationEnabled: true,
  storeRegistrationEnabled: true,
  depositEnabled: true,
  activeHomeTheme: "default",
  defaultThemeMode: "system",
};

export const defaultHomepageSections = [
  {
    key: "hero",
    title: "Alışveriş marketplace",
    description:
      "Azərbaycanda mağaza açmaq, yeni məhsul satmaq və sifarişləri idarə etmək üçün müasir e-ticarət marketplace platforması.",
    imageUrl: "",
    settings: {
      showTitle: true,
      showDescription: true,
    },
    buttonLabel: "Mağazanı aç",
    buttonUrl: "/register?role=seller",
    itemLimit: 1,
    dataFilter: "manual",
    sortOrder: 1,
    isActive: true,
    showMobile: true,
    showDesktop: true,
    themeVariant: "default",
    status: "published",
  },
  {
    key: "categories",
    title: "Kateqoriyalar",
    description: "Axtardığın məhsula daha tez çat.",
    imageUrl: "",
    settings: {
      showTitle: true,
      showDescription: true,
    },
    buttonLabel: "Məhsullar",
    buttonUrl: "/products",
    itemLimit: 8,
    dataFilter: "categories",
    sortOrder: 2,
    isActive: true,
    showMobile: true,
    showDesktop: true,
    themeVariant: "default",
    status: "published",
  },
  {
    key: "featured_products",
    title: "Seçilmiş mağazalar",
    description: "Güvənilən mağazaları ön plana çıxarın.",
    imageUrl: "",
    settings: {
      showTitle: true,
      showDescription: true,
    },
    buttonLabel: "Bütün mağazalar",
    buttonUrl: "/products",
    itemLimit: 8,
    dataFilter: "featured",
    sortOrder: 3,
    isActive: true,
    showMobile: true,
    showDesktop: true,
    themeVariant: "modern-marketplace",
    status: "published",
  },
  {
    key: "new_products",
    title: "Yeni mağazalar",
    description: "Yeni qoşulan mağazaları göstər.",
    imageUrl: "",
    settings: {
      showTitle: true,
      showDescription: true,
    },
    buttonLabel: "Hamısı",
    buttonUrl: "/products",
    itemLimit: 8,
    dataFilter: "new",
    sortOrder: 4,
    isActive: true,
    showMobile: true,
    showDesktop: true,
    themeVariant: "minimal-storefront",
    status: "published",
  },
  {
    key: "benefits",
    title: "Üstünlüklər",
    description: "Marketplace imkanlarını vurğula.",
    imageUrl: "",
    settings: {
      showTitle: true,
      showDescription: true,
    },
    buttonLabel: "Ətraflı",
    buttonUrl: "/about",
    itemLimit: 3,
    dataFilter: "manual",
    sortOrder: 5,
    isActive: true,
    showMobile: true,
    showDesktop: true,
    themeVariant: "bold-catalog",
    status: "published",
  },
] as const;

export const defaultThemeSettings = [
  {
    themeKey: "default",
    name: "Default",
    status: "published",
    isActive: true,
    previewImageUrl: "",
    heroVariant: "default",
    productCardVariant: "default",
    sectionOrder: ["hero", "categories", "featured_products", "new_products", "benefits"],
    config: {},
  },
  {
    themeKey: "modern-marketplace",
    name: "Modern Marketplace",
    status: "published",
    isActive: false,
    previewImageUrl: "",
    heroVariant: "modern",
    productCardVariant: "rounded",
    sectionOrder: ["hero", "featured_products", "categories", "benefits", "new_products"],
    config: {},
  },
  {
    themeKey: "luxury-commerce",
    name: "Luxury Commerce",
    status: "published",
    isActive: false,
    previewImageUrl: "",
    heroVariant: "premium",
    productCardVariant: "elevated",
    sectionOrder: ["hero", "featured_products", "benefits", "categories", "new_products"],
    config: {},
  },
  {
    themeKey: "minimal-storefront",
    name: "Minimal Storefront",
    status: "published",
    isActive: false,
    previewImageUrl: "",
    heroVariant: "minimal",
    productCardVariant: "minimal",
    sectionOrder: ["hero", "categories", "new_products", "featured_products", "benefits"],
    config: {},
  },
  {
    themeKey: "bold-catalog",
    name: "Bold Catalog",
    status: "published",
    isActive: false,
    previewImageUrl: "",
    heroVariant: "bold",
    productCardVariant: "bold",
    sectionOrder: ["hero", "featured_products", "new_products", "benefits", "categories"],
    config: {},
  },
] as const;

export const criticalSellerRoutes = new Set([
  "/admin",
  "/admin/products",
  "/admin/orders",
  "/admin/subscription",
]);

export const criticalCustomerRoutes = new Set([
  "/dashboard",
  "/dashboard/listings",
  "/dashboard/orders",
  "/dashboard/profile",
]);

export function navItemKey(item: DashboardNavItem) {
  return item.href.replace(/^\//, "").replace(/\//g, "_") || "home";
}
