import type { DashboardNavItem } from "@/lib/dashboard/navigation";
import { defaultDesignSettings } from "@/lib/design/presets";
import type { SiteSettings } from "@/lib/cms/types";

export const homeThemeKeys = [
  "default",
  "modern-marketplace",
  "luxury-commerce",
  "minimal-storefront",
  "bold-catalog",
  "liquid-glass",
  "soft-commerce",
  "corporate",
  "elegant",
  "compact",
] as const;

export const defaultHomeThemeColors = {
  pageBackground: "#f8fafc",
  heroBackground: "#f0fdfa",
  categoriesBackground: "#ffffff",
  storesBackground: "#ffffff",
  productsBackground: "#f8fafc",
  benefitsBackground: "#ffffff",
  cardBackground: "#ffffff",
  text: "#0f172a",
  mutedText: "#64748b",
  primary: "#0891b2",
  accent: "#f59e0b",
  buttonBackground: "#0891b2",
  buttonText: "#ffffff",
  border: "#dbe3ea",
} as const;

export const homeThemeColorPresets = {
  default: defaultHomeThemeColors,
  "modern-marketplace": {
    ...defaultHomeThemeColors,
    pageBackground: "#ecfeff",
    heroBackground: "#f0fdfa",
    productsBackground: "#f8fafc",
    primary: "#0891b2",
    accent: "#f59e0b",
    buttonBackground: "#0891b2",
  },
  "luxury-commerce": {
    ...defaultHomeThemeColors,
    pageBackground: "#fafaf9",
    heroBackground: "#fffbeb",
    productsBackground: "#f5f5f4",
    primary: "#92400e",
    accent: "#d97706",
    buttonBackground: "#92400e",
    border: "#e7e5e4",
  },
  "minimal-storefront": {
    ...defaultHomeThemeColors,
    pageBackground: "#ffffff",
    heroBackground: "#f8fafc",
    productsBackground: "#ffffff",
    primary: "#111827",
    accent: "#64748b",
    buttonBackground: "#111827",
  },
  "bold-catalog": {
    ...defaultHomeThemeColors,
    pageBackground: "#fff1f2",
    heroBackground: "#ecfeff",
    productsBackground: "#fff7ed",
    primary: "#e11d48",
    accent: "#0891b2",
    buttonBackground: "#e11d48",
  },
  "liquid-glass": {
    ...defaultHomeThemeColors,
    pageBackground: "#ecfeff",
    heroBackground: "#e6fbff",
    categoriesBackground: "#f8fdff",
    storesBackground: "#f1fcff",
    productsBackground: "#eafcff",
    benefitsBackground: "#f8fdff",
    cardBackground: "#ffffff",
    text: "#071827",
    mutedText: "#4b6473",
    primary: "#06b6d4",
    accent: "#8b5cf6",
    buttonBackground: "#0891b2",
    border: "#bdebf3",
  },
  "soft-commerce": {
    ...defaultHomeThemeColors,
    pageBackground: "#fbfdfc",
    heroBackground: "#eefbf7",
    productsBackground: "#f6faf8",
    primary: "#0d9488",
    accent: "#eab308",
    buttonBackground: "#0d9488",
    border: "#dde8e5",
  },
  corporate: {
    ...defaultHomeThemeColors,
    pageBackground: "#f8fafc",
    heroBackground: "#eef6fb",
    productsBackground: "#f8fafc",
    primary: "#155e75",
    accent: "#0ea5e9",
    buttonBackground: "#155e75",
    border: "#d6dee8",
  },
  elegant: {
    ...defaultHomeThemeColors,
    pageBackground: "#fafafa",
    heroBackground: "#f7f7f5",
    productsBackground: "#ffffff",
    primary: "#115e59",
    accent: "#a16207",
    buttonBackground: "#115e59",
    border: "#e4e4e7",
  },
  compact: {
    ...defaultHomeThemeColors,
    pageBackground: "#f8fafc",
    heroBackground: "#f1f5f9",
    productsBackground: "#f8fafc",
    primary: "#0f766e",
    accent: "#f59e0b",
    buttonBackground: "#0f766e",
    border: "#d7dde5",
  },
} as const;

export const defaultSiteSettings: SiteSettings = {
  siteName: "Alışveriş",
  shortName: "Alışveriş",
  logoUrl: "",
  darkLogoUrl: "",
  faviconUrl: "",
  defaultSeoTitle: "Alışveriş - Marketplace, mağaza və elan platforması",
  defaultMetaDescription:
    "Azərbaycanda məhsul satışı, mağaza idarəetməsi, elan yerləşdirmə və sifarişlər üçün marketplace platforması.",
  defaultSeoKeywords:
    "alışveriş, marketplace, məhsul satışı, elan, mağaza",
  contactEmail: "",
  phone: "",
  whatsapp: "",
  address: "",
  socialLinks: {},
  copyrightText: "© Alışveriş",
  maintenanceMode: false,
  userRegistrationEnabled: true,
  storeRegistrationEnabled: true,
  depositEnabled: false,
  showSubscriptionInSellerPanel: false,
  subscriptionsDisabledForSellers: true,
  globalLoader: {
    type: "classic",
    palette: "primary",
  },
  mobileNavbarVariant: "classic",
  subscriptionLimits: {
    defaultProductLimit: 100,
    defaultImagesPerProductLimit: 5,
  },
  design: defaultDesignSettings,
  activeHomeTheme: "default",
  defaultThemeMode: "system",
};

export const defaultHomepageSections = [
  {
    key: "hero",
    title: "Alışveriş marketplace",
    description:
      "Azərbaycanda mağaza açmaq, yeni məhsul satmaq və sifarişləri idarə etmək üçün müasir e-ticarət marketplace platforması.",
    imageUrl: "",
    settings: {
      showTitle: true,
      showDescription: true,
    },
    buttonLabel: "Mağazanı aç",
    buttonUrl: "/register?role=seller",
    itemLimit: 1,
    dataFilter: "manual",
    sortOrder: 1,
    isActive: true,
    showMobile: true,
    showDesktop: true,
    themeVariant: "default",
    status: "published",
  },
  {
    key: "categories",
    title: "Kateqoriyalar",
    description: "Axtardığın məhsula daha tez çat.",
    imageUrl: "",
    settings: {
      showTitle: true,
      showDescription: true,
    },
    buttonLabel: "Məhsullar",
    buttonUrl: "/products",
    itemLimit: 8,
    dataFilter: "categories",
    sortOrder: 2,
    isActive: true,
    showMobile: true,
    showDesktop: true,
    themeVariant: "default",
    status: "published",
  },
  {
    key: "featured_products",
    title: "Seçilmiş mağazalar",
    description: "Güvənilən mağazaları ön plana çıxarın.",
    imageUrl: "",
    settings: {
      showTitle: true,
      showDescription: true,
    },
    buttonLabel: "Bütün mağazalar",
    buttonUrl: "/products",
    itemLimit: 8,
    dataFilter: "featured",
    sortOrder: 3,
    isActive: true,
    showMobile: true,
    showDesktop: true,
    themeVariant: "modern-marketplace",
    status: "published",
  },
  {
    key: "new_products",
    title: "Yeni mağazalar",
    description: "Yeni qoşulan mağazaları göstər.",
    imageUrl: "",
    settings: {
      showTitle: true,
      showDescription: true,
    },
    buttonLabel: "Hamısı",
    buttonUrl: "/products",
    itemLimit: 8,
    dataFilter: "new",
    sortOrder: 4,
    isActive: true,
    showMobile: true,
    showDesktop: true,
    themeVariant: "minimal-storefront",
    status: "published",
  },
  {
    key: "benefits",
    title: "Üstünlüklər",
    description: "Marketplace imkanlarını vurğula.",
    imageUrl: "",
    settings: {
      showTitle: true,
      showDescription: true,
    },
    buttonLabel: "Ətraflı",
    buttonUrl: "/about",
    itemLimit: 3,
    dataFilter: "manual",
    sortOrder: 5,
    isActive: true,
    showMobile: true,
    showDesktop: true,
    themeVariant: "bold-catalog",
    status: "published",
  },
] as const;

export const defaultThemeSettings = [
  {
    themeKey: "default",
    name: "Default",
    status: "published",
    isActive: true,
    previewImageUrl: "",
    heroVariant: "default",
    productCardVariant: "default",
    sectionOrder: ["hero", "categories", "featured_products", "new_products", "benefits"],
    config: { colors: homeThemeColorPresets.default },
  },
  {
    themeKey: "modern-marketplace",
    name: "Modern Marketplace",
    status: "published",
    isActive: false,
    previewImageUrl: "",
    heroVariant: "modern",
    productCardVariant: "rounded",
    sectionOrder: ["hero", "featured_products", "categories", "benefits", "new_products"],
    config: { colors: homeThemeColorPresets["modern-marketplace"] },
  },
  {
    themeKey: "luxury-commerce",
    name: "Luxury Commerce",
    status: "published",
    isActive: false,
    previewImageUrl: "",
    heroVariant: "premium",
    productCardVariant: "elevated",
    sectionOrder: ["hero", "featured_products", "benefits", "categories", "new_products"],
    config: { colors: homeThemeColorPresets["luxury-commerce"] },
  },
  {
    themeKey: "minimal-storefront",
    name: "Minimal Storefront",
    status: "published",
    isActive: false,
    previewImageUrl: "",
    heroVariant: "minimal",
    productCardVariant: "minimal",
    sectionOrder: ["hero", "categories", "new_products", "featured_products", "benefits"],
    config: { colors: homeThemeColorPresets["minimal-storefront"] },
  },
  {
    themeKey: "bold-catalog",
    name: "Bold Catalog",
    status: "published",
    isActive: false,
    previewImageUrl: "",
    heroVariant: "bold",
    productCardVariant: "bold",
    sectionOrder: ["hero", "featured_products", "new_products", "benefits", "categories"],
    config: { colors: homeThemeColorPresets["bold-catalog"] },
  },
  {
    themeKey: "liquid-glass",
    name: "Liquid Glass",
    status: "published",
    isActive: false,
    previewImageUrl: "",
    heroVariant: "liquid",
    productCardVariant: "liquid-glass",
    sectionOrder: ["hero", "featured_products", "categories", "new_products", "benefits"],
    config: { colors: homeThemeColorPresets["liquid-glass"] },
  },
  {
    themeKey: "soft-commerce",
    name: "Soft Commerce",
    status: "published",
    isActive: false,
    previewImageUrl: "",
    heroVariant: "default",
    productCardVariant: "classic",
    sectionOrder: ["hero", "categories", "featured_products", "new_products", "benefits"],
    config: { colors: homeThemeColorPresets["soft-commerce"] },
  },
  {
    themeKey: "corporate",
    name: "Corporate",
    status: "published",
    isActive: false,
    previewImageUrl: "",
    heroVariant: "minimal",
    productCardVariant: "compact",
    sectionOrder: ["hero", "categories", "featured_products", "benefits", "new_products"],
    config: { colors: homeThemeColorPresets.corporate },
  },
  {
    themeKey: "elegant",
    name: "Elegant",
    status: "published",
    isActive: false,
    previewImageUrl: "",
    heroVariant: "premium",
    productCardVariant: "borderless",
    sectionOrder: ["hero", "featured_products", "categories", "benefits", "new_products"],
    config: { colors: homeThemeColorPresets.elegant },
  },
  {
    themeKey: "compact",
    name: "Compact",
    status: "published",
    isActive: false,
    previewImageUrl: "",
    heroVariant: "minimal",
    productCardVariant: "dense-marketplace",
    sectionOrder: ["hero", "categories", "new_products", "featured_products", "benefits"],
    config: { colors: homeThemeColorPresets.compact },
  },
] as const;

export const criticalSellerRoutes = new Set([
  "/admin",
  "/admin/products",
  "/admin/orders",
  "/admin/subscription",
]);

export const criticalCustomerRoutes = new Set([
  "/dashboard",
  "/dashboard/listings",
  "/dashboard/orders",
  "/dashboard/profile",
]);

export function navItemKey(item: DashboardNavItem) {
  return item.href.replace(/^\//, "").replace(/\//g, "_") || "home";
}
